---
- hosts: localhost
  tasks:
          #- name: pull image
          # docker_image:
          #         name: aswathanarayanan/test1:test
          # become: yes
          
          - name: Create container
            docker_container:
                    name: calculator
                    image: aswathanarayanan/test1
                    state: started
                    command: /bin/bash
            become_user: jenkins

