---
- hosts: localhost
  tasks:
          - name: remove comtainer
            shell: |
                    docker rmi $(docker images -q aswathanarayanan/test1:latest)
                    docker rm calculator
            become_user: jenkins
            ignore_errors: true

          - name: pull image
            docker_image:
                name: aswathanarayanan/test1:test
                #become: yes
            become_user: jenkins
            
          - name: Run docker
            shell: docker create -it --name calculator aswathanarayanan/test1
            #become: yes
            become_user: jenkins

            #- name: Print
            #shell: echo "hello"
          
         # - name: Create container
         #   docker_container:
         #           name: calculator
         #           image: aswathanarayanan/test1
         #           state: started
                    #command: /bin/bash
         #   become: yes
         #   become_user: jenkins

