---
- hosts: localhost
  tasks:
          - name: pull image
            docker_image:
                name: aswathanarayanan/test1:test
            become: yes
            
          - name: Run docker
            shell: docker create -it --name calculator aswathanarayanan/test1
            become: yes
          
         # - name: Create container
         #   docker_container:
         #           name: calculator
         #           image: aswathanarayanan/test1
         #           state: started
                    #command: /bin/bash
         #   become: yes
         #   become_user: jenkins

